DROP TABLE LIQUISHOP.DEVELOP.UNIT CASCADE;
DROP TABLE LIQUISHOP.DEVELOP.ORDER CASCADE;
DROP TABLE LIQUISHOP.DEVELOP.PRODUCT CASCADE;
DROP TABLE LIQUISHOP.DEVELOP.ORDER_JUNCTION CASCADE;
DROP SCHEMA DEVELOP CASCADE;